<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ArticleSeeder extends Seeder {

    public function run(): void{
        DB::table('articles')->insert([
            [
                'user_id' => 1,
                'category_id' => 1,
                'title' => 'Getting Started with Laravel',
                'slug' => Str::slug('Getting Started with Laravel'),
                'content' => 'This is a beginner guide to Laravel framework.',
                'image' => null,
                'published_at' => now(),
                'status' => 'published',
                'tags' => 'laravel,php,backend',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'category_id' => 2,
                'title' => 'Understanding REST API',
                'slug' => Str::slug('Understanding REST API'),
                'content' => 'REST API concepts explained simply.',
                'image' => null,
                'published_at' => now(),
                'status' => 'published',
                'tags' => 'api,rest,backend',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'category_id' => 1,
                'title' => 'Laravel Routing Basics',
                'slug' => Str::slug('Laravel Routing Basics'),
                'content' => 'Learn how routing works in Laravel.',
                'image' => null,
                'published_at' => now(),
                'status' => 'draft',
                'tags' => 'laravel,routing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'category_id' => 3,
                'title' => 'Authentication with Sanctum',
                'slug' => Str::slug('Authentication with Sanctum'),
                'content' => 'Secure API authentication using Sanctum.',
                'image' => null,
                'published_at' => now(),
                'status' => 'published',
                'tags' => 'laravel,sanctum,auth',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'category_id' => 2,
                'title' => 'Database Migration Guide',
                'slug' => Str::slug('Database Migration Guide'),
                'content' => 'How to use migrations in Laravel.',
                'image' => null,
                'published_at' => now(),
                'status' => 'pending',
                'tags' => 'database,migration',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'category_id' => 1,
                'title' => 'Eloquent ORM Basics',
                'slug' => Str::slug('Eloquent ORM Basics'),
                'content' => 'Learn about Laravel Eloquent ORM.',
                'image' => null,
                'published_at' => now(),
                'status' => 'published',
                'tags' => 'eloquent,laravel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'category_id' => 2,
                'title' => 'API Authentication Best Practices',
                'slug' => Str::slug('API Authentication Best Practices'),
                'content' => 'Best practices for securing APIs.',
                'image' => null,
                'published_at' => now(),
                'status' => 'draft',
                'tags' => 'api,security',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'category_id' => 3,
                'title' => 'Laravel Validation Explained',
                'slug' => Str::slug('Laravel Validation Explained'),
                'content' => 'Validation rules in Laravel.',
                'image' => null,
                'published_at' => now(),
                'status' => 'published',
                'tags' => 'validation,laravel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'category_id' => 1,
                'title' => 'Working with Middleware',
                'slug' => Str::slug('Working with Middleware'),
                'content' => 'Middleware usage in Laravel.',
                'image' => null,
                'published_at' => now(),
                'status' => 'pending',
                'tags' => 'middleware,laravel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'category_id' => 2,
                'title' => 'Deploying Laravel Project',
                'slug' => Str::slug('Deploying Laravel Project'),
                'content' => 'Steps to deploy Laravel app.',
                'image' => null,
                'published_at' => now(),
                'status' => 'published',
                'tags' => 'deployment,laravel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
